=== l3miage-koneze/Projet-Voyageur-De-Sante/src/data/xsd/patient.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--

Authors : Zeinabou Bissi KONE - Sicong XU

-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:pat="http://www.ujf-grenoble.fr/l3miage/medical"
           targetNamespace="http://www.ujf-grenoble.fr/l3miage/medical"
           elementFormDefault="qualified">
    
    
    <!--.................RACINE : Patient..........................-->
    
    <xs:element name="patient" type="pat:Patient"/>
    
    
    <!--..............Définition du type Patient..................-->
    
     <xs:complexType name="Patient">
        <xs:sequence>
            <xs:element name="nom" type="pat:NomEtPrénom"/>
            <xs:element name="prénom" type="pat:NomEtPrénom"/>
            <xs:element name="sexe" type="pat:Sexe"/>
            <xs:element name="naissance" type="xs:date"/>
            <xs:element name="numéro" type="pat:NuméroSecu"/>
            <xs:element name="adresse" type="pat:Adresse"/>
            <xs:element name="visite" type="pat:Visite" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    
    
    <!--.................Définition du type NomEtPrénom.............-->
    
    <xs:simpleType name="NomEtPrénom">
        <xs:restriction base="xs:string">
             <xs:pattern value="([A-Z])([a-zéèàùâûôêäëïöüçỹ])*((\s||-)([A-Z])([a-zéèàùâûôêäëïöüçỹ]))*"/>
             <xs:pattern value=""/>
        </xs:restriction>
    </xs:simpleType>
    


    
    <!--..............Définition du type Adresse..............-->
    
    <xs:complexType name="Adresse">
        <xs:sequence>
            <xs:element name="étage" type="pat:Etage" minOccurs="0" maxOccurs="1"/>
            <xs:element name="numéro" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="rue" type="xs:string"/>
            <xs:element name="ville" type="pat:Ville"/>
            <xs:element name="codePostal" type="pat:CodePostal"/>
        </xs:sequence>
    </xs:complexType>
    
    
    
    
    <!--..............Définition du type Etage (RDC = Rez-De-Chaussée).................-->
    
    <xs:simpleType name="Etage">
        <xs:restriction base="xs:string">
            <xs:pattern value="((RDC)|([\d])*)" />
        </xs:restriction>
    </xs:simpleType>
    
    
    
    
    <!--................Définition du type Ville.................-->

    <xs:simpleType name="Ville">
        <xs:restriction base="xs:string">
           <xs:pattern value="(([A-Z])([a-zéèàùâûôêäëïöüçỹ])*)((\s)(([A-Z])([a-zéèàùâûôêäëïöüçỹ])*))*"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    
    
    <!--............Definition du type CodePostal..............-->
    
    <xs:simpleType name="CodePostal">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{5}"/>
        </xs:restriction>
    </xs:simpleType>



   <!--...........................Définition du type Sexe............-->
   
    <xs:simpleType name="Sexe">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M"/>
            <xs:enumeration value="F"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    
    <!--......................Définition du type NuméroSecu....................-->
    
    <xs:simpleType name="NuméroSecu">
        <xs:restriction base="xs:string">
            <xs:pattern value="((1|2)([\d]){2}(0|1)([1|2|3|4|5|6|7|8|9])([\d]){10})"/>
        </xs:restriction>
    </xs:simpleType>



    <!--..........................Définition du type Visite................-->
    
    <xs:complexType name="Visite">
        <xs:sequence>
            <xs:element name="intervenant" type="pat:Intervenant" minOccurs="0" maxOccurs="1"/>
            <xs:element name="acte" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="date" type="xs:date"/>
    </xs:complexType>
    
    
    <!--.......................Définition du type Intervenant................-->
    
    <xs:complexType name="Intervenant">
        <xs:sequence>
            <xs:element name="nom" type="pat:NomEtPrénom"/>
            <xs:element name="prénom" type="pat:NomEtPrénom"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== l3miage-koneze/Projet-Voyageur-De-Sante/src/data/xml/patient_ALECOLE.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

Authors : Zeinabou Bissi KONE - Sicong XU

-->

<patient xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
         xmlns:act="http://www.ujf-grenoble.fr/l3miage/actes" 
         xmlns='http://www.ujf-grenoble.fr/l3miage/medical'
         xsi:schemaLocation='http://www.ujf-grenoble.fr/l3miage/medical ../xsd/patient.xsd'>
    <nom>Alécole</nom>
    <prénom>Yvon</prénom>
    <sexe>M</sexe>
    <naissance>1998-08-02</naissance>
    <numéro>198081305545892</numéro>
    <adresse>
        <étage>6</étage>
        <numéro>50</numéro>
        <rue>avenue Félix Viallet</rue>
        <ville>Grenoble</ville>
        <codePostal>38031</codePostal>
    </adresse>
    <visite date="2015-12-08">
        <intervenant>
            <nom>Fréchie</nom>
            <prénom>Sarah</prénom>
        </intervenant>
        <acte>
            Injection sous-cutanée.
        </acte>
    </visite>
</patient>

=== l3miage-koneze/Projet-Voyageur-De-Sante/src/data/xml/patient_PIEN.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

Authors : Zeinabou Bissi KONE - Sicong XU

-->

<patient xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
         xmlns:act="http://www.ujf-grenoble.fr/l3miage/actes" 
         xmlns='http://www.ujf-grenoble.fr/l3miage/medical'
         xsi:schemaLocation='http://www.ujf-grenoble.fr/l3miage/medical ../xsd/patient.xsd'>
    
    
    <nom>Pien</nom>
    <prénom>Oscare</prénom>
    <sexe>F</sexe>
    <naissance>1975-03-25</naissance>
    <numéro>275037306569202</numéro>
    <adresse>
        <étage/>
        <numéro/>
        <rue>rue Casimir Brenier</rue>
        <ville>Grenoble</ville>
        <codePostal>38000</codePostal>
    </adresse>
    <visite date="2015-12-08">
        <intervenant>
            <nom/>
            <prénom/>
        </intervenant>
        <acte> 
            Prélèvement par ponction veineuse directe
        </acte>
        <acte>
            Inection intraveineuse directe isolée.
        </acte>
    </visite>
</patient>

=== l3miage-koneze/Projet-Voyageur-De-Sante/src/data/xml/patient_OROUGE.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

Authors : Zeinabou Bissi KONE - Sicong XU

-->

<patient xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
         xmlns:act="http://www.ujf-grenoble.fr/l3miage/actes" 
         xmlns='http://www.ujf-grenoble.fr/l3miage/medical'
         xsi:schemaLocation='http://www.ujf-grenoble.fr/l3miage/medical ../xsd/patient.xsd'>
    <nom>Orouge</nom>
    <prénom>Elvire</prénom>
    <sexe>F</sexe>
    <naissance>1982-03-08</naissance>
    <numéro>282036912305225</numéro>
    <adresse>
        <étage/>
        <numéro/>
        <rue>Rond-Point de la Croix de Vie</rue>
        <ville>La Tronche</ville>
        <codePostal>38700</codePostal>
    </adresse>
    <visite date="2015-12-08">
        <intervenant>
            <nom/>
            <prénom/>
        </intervenant>
        <acte>
            Pansement de brûlure étendue ou de plaie chimique ou thermique étendue,
            sur une surface supérieure à 5% de la surface corporelle.
        </acte>
    </visite>
</patient>

=== l3miage-koneze/Projet-Voyageur-De-Sante/src/data/xml/patient_KAPOETLA.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

Authors : Zeinabou Bissi KONE - Sicong XU

-->


<patient xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
         xmlns:act="http://www.ujf-grenoble.fr/l3miage/actes" 
         xmlns='http://www.ujf-grenoble.fr/l3miage/medical'
         xsi:schemaLocation='http://www.ujf-grenoble.fr/l3miage/medical ../xsd/patient.xsd'>
    <nom>Kapoëtla</nom>
    <prénom>Xavier</prénom>
    <sexe>M</sexe>
    <naissance>2011-08-02</naissance>
    <numéro>111083306303521</numéro>
    <adresse>
        <étage/>
        <numéro>25</numéro>
        <rue>rue des Martyrs</rue>
        <ville>Grenoble</ville>
        <codePostal>38042</codePostal>
    </adresse>
    <visite date="2015-12-08">
        <intervenant>
            <nom/>
            <prénom/>
        </intervenant>
        <acte>
            Injection d'un ou plusieurs allergènes, poursuivant un traitement
            d'hyposensibilisation spécifique, selon le protocole écrit, y compris la
            surveillance, la tenue du dossier de soins, la transmission des informations 
            au médecin prescripteur.
        </acte>
    </visite>
</patient>
